# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_FirTuner.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FirTuner(object):
    def setupUi(self, FirTuner):
        FirTuner.setObjectName("FirTuner")
        FirTuner.resize(730, 712)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FirTuner.sizePolicy().hasHeightForWidth())
        FirTuner.setSizePolicy(sizePolicy)
        FirTuner.setMinimumSize(QtCore.QSize(730, 700))
        FirTuner.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gridLayout = QtWidgets.QGridLayout(FirTuner)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_mpl = QtWidgets.QWidget(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_mpl.sizePolicy().hasHeightForWidth())
        self.widget_mpl.setSizePolicy(sizePolicy)
        self.widget_mpl.setMinimumSize(QtCore.QSize(500, 350))
        self.widget_mpl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_mpl.setObjectName("widget_mpl")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_mpl)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.layout_mpl = QtWidgets.QVBoxLayout()
        self.layout_mpl.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.layout_mpl.setSpacing(0)
        self.layout_mpl.setObjectName("layout_mpl")
        self.gridLayout_2.addLayout(self.layout_mpl, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_mpl)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_n = QtWidgets.QLineEdit(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_n.sizePolicy().hasHeightForWidth())
        self.lineEdit_n.setSizePolicy(sizePolicy)
        self.lineEdit_n.setMinimumSize(QtCore.QSize(150, 20))
        self.lineEdit_n.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.horizontalLayout.addWidget(self.lineEdit_n)
        self.line = QtWidgets.QFrame(FirTuner)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.label_3 = QtWidgets.QLabel(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 25))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_fp = QtWidgets.QLineEdit(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fp.sizePolicy().hasHeightForWidth())
        self.lineEdit_fp.setSizePolicy(sizePolicy)
        self.lineEdit_fp.setMinimumSize(QtCore.QSize(150, 20))
        self.lineEdit_fp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fp.setObjectName("lineEdit_fp")
        self.horizontalLayout.addWidget(self.lineEdit_fp)
        self.line_2 = QtWidgets.QFrame(FirTuner)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.label = QtWidgets.QLabel(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 25))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_fc = QtWidgets.QLineEdit(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_fc.sizePolicy().hasHeightForWidth())
        self.lineEdit_fc.setSizePolicy(sizePolicy)
        self.lineEdit_fc.setMinimumSize(QtCore.QSize(150, 20))
        self.lineEdit_fc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_fc.setObjectName("lineEdit_fc")
        self.horizontalLayout.addWidget(self.lineEdit_fc)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 25))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.button_printCoefficients = QtWidgets.QPushButton(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_printCoefficients.sizePolicy().hasHeightForWidth())
        self.button_printCoefficients.setSizePolicy(sizePolicy)
        self.button_printCoefficients.setObjectName("button_printCoefficients")
        self.horizontalLayout_3.addWidget(self.button_printCoefficients)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(FirTuner)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.groupBox_filterType = QtWidgets.QGroupBox(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_filterType.sizePolicy().hasHeightForWidth())
        self.groupBox_filterType.setSizePolicy(sizePolicy)
        self.groupBox_filterType.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox_filterType.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_filterType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_filterType.setFlat(False)
        self.groupBox_filterType.setCheckable(False)
        self.groupBox_filterType.setObjectName("groupBox_filterType")
        self.radioButton_lowpass = QtWidgets.QRadioButton(self.groupBox_filterType)
        self.radioButton_lowpass.setGeometry(QtCore.QRect(110, 40, 100, 20))
        self.radioButton_lowpass.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_lowpass.setCheckable(True)
        self.radioButton_lowpass.setChecked(True)
        self.radioButton_lowpass.setObjectName("radioButton_lowpass")
        self.radioButton_bandpass = QtWidgets.QRadioButton(self.groupBox_filterType)
        self.radioButton_bandpass.setGeometry(QtCore.QRect(310, 40, 100, 20))
        self.radioButton_bandpass.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_bandpass.setChecked(False)
        self.radioButton_bandpass.setObjectName("radioButton_bandpass")
        self.radioButton_highpass = QtWidgets.QRadioButton(self.groupBox_filterType)
        self.radioButton_highpass.setGeometry(QtCore.QRect(490, 40, 100, 20))
        self.radioButton_highpass.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_highpass.setObjectName("radioButton_highpass")
        self.radioButton_lowpass.raise_()
        self.radioButton_bandpass.raise_()
        self.radioButton_highpass.raise_()
        self.horizontalLayout_6.addWidget(self.groupBox_filterType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_windowType = QtWidgets.QGroupBox(FirTuner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_windowType.sizePolicy().hasHeightForWidth())
        self.groupBox_windowType.setSizePolicy(sizePolicy)
        self.groupBox_windowType.setMinimumSize(QtCore.QSize(0, 75))
        self.groupBox_windowType.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_windowType.setFlat(False)
        self.groupBox_windowType.setObjectName("groupBox_windowType")
        self.radioButton_hamming = QtWidgets.QRadioButton(self.groupBox_windowType)
        self.radioButton_hamming.setGeometry(QtCore.QRect(110, 40, 100, 20))
        self.radioButton_hamming.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_hamming.setObjectName("radioButton_hamming")
        self.radioButton_blackman = QtWidgets.QRadioButton(self.groupBox_windowType)
        self.radioButton_blackman.setGeometry(QtCore.QRect(310, 40, 100, 20))
        self.radioButton_blackman.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_blackman.setObjectName("radioButton_blackman")
        self.radioButton_rectangular = QtWidgets.QRadioButton(self.groupBox_windowType)
        self.radioButton_rectangular.setGeometry(QtCore.QRect(490, 40, 100, 20))
        self.radioButton_rectangular.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButton_rectangular.setChecked(True)
        self.radioButton_rectangular.setObjectName("radioButton_rectangular")
        self.horizontalLayout_2.addWidget(self.groupBox_windowType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)

        self.retranslateUi(FirTuner)
        QtCore.QMetaObject.connectSlotsByName(FirTuner)

    def retranslateUi(self, FirTuner):
        _translate = QtCore.QCoreApplication.translate
        FirTuner.setWindowTitle(_translate("FirTuner", "FirTunerWidget"))
        self.label_2.setText(_translate("FirTuner", "N:"))
        self.lineEdit_n.setPlaceholderText(_translate("FirTuner", "Order"))
        self.label_3.setText(_translate("FirTuner", "fp [Hz]:"))
        self.lineEdit_fp.setPlaceholderText(_translate("FirTuner", "Passband in kHz"))
        self.label.setText(_translate("FirTuner", "fc [Hz]:"))
        self.lineEdit_fc.setPlaceholderText(_translate("FirTuner", "Center in kHz"))
        self.label_4.setText(_translate("FirTuner", "<html><head/><body><p><span style=\" font-style:italic;\">Press ENTER to update parameters.</span></p></body></html>"))
        self.button_printCoefficients.setText(_translate("FirTuner", "Print Coefficients"))
        self.groupBox_filterType.setTitle(_translate("FirTuner", "Filter Type"))
        self.radioButton_lowpass.setText(_translate("FirTuner", "LowPass"))
        self.radioButton_bandpass.setText(_translate("FirTuner", "BandPass"))
        self.radioButton_highpass.setText(_translate("FirTuner", "HighPass"))
        self.groupBox_windowType.setTitle(_translate("FirTuner", "Window Type"))
        self.radioButton_hamming.setText(_translate("FirTuner", "Hamming"))
        self.radioButton_blackman.setText(_translate("FirTuner", "Blackman"))
        self.radioButton_rectangular.setText(_translate("FirTuner", "Rectangular"))

